#!/usr/bin/env python3
"""
Find DB books with covers that are NOT present anywhere in an Excel workbook.

This script uses the exported covers mapping file (TSV) created by:
  php artisan books:export-covers-by-title

Definition of "present in Excel":
  - We scan all sheets (default) and all cells up to --max-cols per row
  - We compare using aggressive Arabic-friendly normalization:
    hamza variants -> ا, ة->ه, ى->ي, remove diacritics, remove punctuation, collapse spaces
  - If a normalized book title equals a normalized cell value anywhere in the workbook,
    we consider it "present".

Usage (from waha-darin/):
  PYTHONPATH=./.pydeps python3 scripts/covers_not_in_excel.py \
    --excel "storage/app/public/book-covers-by-title/SicherheitsKopie von Darbooks_final_books.xlsx" \
    --mapping "storage/app/public/book-covers-by-title/_mapping.tsv" \
    --out "storage/app/public/book-covers-by-title/_covers_not_found_in_excel.tsv"
"""

from __future__ import annotations

import argparse
import re
import unicodedata
from pathlib import Path


AR_DIACRITICS_RE = re.compile(r"[\u0610-\u061A\u064B-\u065F\u0670\u06D6-\u06ED]")
AR_MAP = str.maketrans(
    {
        "أ": "ا",
        "إ": "ا",
        "آ": "ا",
        "ٱ": "ا",
        "ؤ": "و",
        "ئ": "ي",
        "ى": "ي",
        "ة": "ه",
        "ـ": "",
    }
)
NON_WORD_RE = re.compile(r"[^\w\s]+", re.UNICODE)


def tsv_unescape(s: str) -> str:
    return s.replace("\\t", "\t").replace("\\r", "\r").replace("\\n", "\n")


def tsv_escape(s: str) -> str:
    return str(s).replace("\t", "\\t").replace("\r", "\\r").replace("\n", "\\n")


def norm(s: str) -> str:
    s = tsv_unescape(str(s))
    s = unicodedata.normalize("NFKC", s)
    s = s.replace("\u00A0", " ")
    s = s.translate(AR_MAP)
    s = AR_DIACRITICS_RE.sub("", s)
    s = s.strip()
    s = NON_WORD_RE.sub(" ", s)
    s = re.sub(r"\s+", " ", s, flags=re.UNICODE).strip()
    return s.casefold()


def build_excel_value_set(excel_path: Path, max_cols: int) -> set[str]:
    try:
        from openpyxl import load_workbook  # type: ignore
    except Exception as e:
        raise SystemExit(
            "Missing dependency: openpyxl.\n"
            "Install locally into .pydeps:\n"
            "  python3 -m pip install -t ./.pydeps openpyxl\n"
            f"Original error: {e}"
        )

    wb = load_workbook(excel_path, read_only=True, data_only=True)
    values: set[str] = set()

    for sheet_name in wb.sheetnames:
        ws = wb[sheet_name]
        for row in ws.iter_rows(min_row=1, max_col=max_cols, values_only=True):
            for v in row:
                if v is None or isinstance(v, bool):
                    continue
                s = str(v).strip()
                if not s or s in {"True", "False"}:
                    continue
                n = norm(s)
                if n:
                    values.add(n)

    wb.close()
    return values


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--excel", required=True, help="Path to .xlsx file")
    p.add_argument("--mapping", required=True, help="Path to _mapping.tsv generated by export command")
    p.add_argument("--out", required=True, help="Output TSV path")
    p.add_argument("--max-cols", type=int, default=30, help="Max columns per row to scan (default: 30)")
    args = p.parse_args()

    excel_path = Path(args.excel)
    mapping_path = Path(args.mapping)
    out_path = Path(args.out)

    if not excel_path.exists():
        raise SystemExit(f"Excel not found: {excel_path}")
    if not mapping_path.exists():
        raise SystemExit(f"Mapping not found: {mapping_path}")

    excel_values = build_excel_value_set(excel_path, max_cols=args.max_cols)

    lines = mapping_path.read_text(encoding="utf-8", errors="replace").splitlines()
    if not lines:
        raise SystemExit(f"Empty mapping file: {mapping_path}")

    header = lines[0].split("\t")
    try:
        idx_id = header.index("book_id")
        idx_title = header.index("book_title")
        idx_new = header.index("new_rel_path")
        idx_src = header.index("src_rel_path")
    except ValueError as e:
        raise SystemExit(f"Unexpected mapping header. Found: {header}\nError: {e}")

    missing_rows = []
    total = 0
    found = 0

    for ln in lines[1:]:
        if not ln.strip():
            continue
        parts = ln.split("\t")
        if len(parts) < len(header):
            continue

        total += 1
        book_id = tsv_unescape(parts[idx_id])
        title = tsv_unescape(parts[idx_title])
        newp = tsv_unescape(parts[idx_new])
        srcp = tsv_unescape(parts[idx_src])

        if norm(title) in excel_values:
            found += 1
        else:
            missing_rows.append((book_id, title, newp, srcp))

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as out:
        out.write("\t".join(["book_id", "book_title", "new_rel_path", "src_rel_path"]) + "\n")
        for book_id, title, newp, srcp in missing_rows:
            out.write(
                "\t".join(
                    [tsv_escape(book_id), tsv_escape(title), tsv_escape(newp), tsv_escape(srcp)]
                )
                + "\n"
            )

    print(f"DB covers (rows in mapping): {total}")
    print(f"Found in Excel (any cell, normalized): {found}")
    print(f"NOT found in Excel: {len(missing_rows)}")
    print(f"Wrote: {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

